### ISSUE TITLE
Minus sign problem

### ISSUE THREAD

**Issue by phrwtz** [concord-consortium/teaching-teamwork#3]
The DMM doesn't show

**Comment by dougmartin** [comment]
This has been fixed in the breadboard code.  To pull the changed code in do the following in a terminal window:

    bower update
    npm start

The "bower update" will pull in the new breadboard code and the "npm start" will copy the code to the dist folder.

**Comment by phrwtz** [comment]
But folks running the code directly from our server will see it, no? Which
brings up another problem: when I go to
http://concord-consortium.github.io/teaching-teamwork/#three-resistors I
get the same "failed to load resource" error that we were getting
yesterday. (Sorry, this is the first time I've tried it since we spoke.) I
thought that link was the "public" one that the project was using for the
official version.

Can you see what's wrong?

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Comment by dougmartin** [comment]
Hi Paul,

I don't have access to update the deployment branch which is what is used to create the content on the github.io page.

**Comment by phrwtz** [comment]
Have you asked Sam Fentress for access?

Paul



Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Comment by dougmartin** [comment]
He wants me to do pull requests for now.  I'll ask him to update the github.io page.

**Comment by phrwtz** [comment]
You should definitely have access to the deployment branch so that the
other members of the project (located, variously, at Tidewater Community
College in Virginia Beach, CORD in Waco, Weber State University in Ogden,
and Minuteman High School in Lexington) can get the latest and greatest of
everything.


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Comment by phrwtz** [comment]
OK, that's fine. But yes, do do pull requests so that our friends can see
all the good work you're doing.

In the meantime, how do I get to see your commits?

Paul



Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Comment by dougmartin** [comment]
The changes were made in the breadboard repo.  Here is the pull request:

https://github.com/concord-consortium/breadboard/pull/1

**Comment by phrwtz** [comment]
OK, I see them now. Cool!

I've got a very peculiar bug for you, if you're interested. It's produced
by the attached JSON script.

As you'll see if you run it"

if you put the DMM probes across the external DC source (the red and blue
wires that come in from off the breadboard) you read 12.5, which is correct.

If you measure from the right end of the red wire to the black wire you
also get 12.5 volts

BUT if you measure from either end of the resistor (or from the left end of
the red wire) to the black wire, you get zero volts!!!

If you disconnect the resistor (which you can do by clicking on its right
lead) the voltage between the left end of the red wire and the black wire
goes back to 12.5 volts -- which ought to indicate a 12.5 volt drop across
a (zero resistance) wire!

I've got to go to a meeting now, but I'll leave you with that mystery.
I'll be back.

Paul




Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson
